# Generated by Django 4.2.7 on 2023-11-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MunDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('slogan', models.CharField(max_length=255)),
                ('noOfWards', models.IntegerField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('president', models.CharField(max_length=30)),
                ('presidentContact', models.CharField(max_length=10)),
                ('presidentImage', models.ImageField(upload_to='images/')),
                ('secretary', models.CharField(max_length=30)),
                ('secretaryContact', models.CharField(max_length=10)),
                ('secretaryImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPopulation', models.IntegerField()),
                ('malePopulation', models.IntegerField()),
                ('femalePopulation', models.IntegerField()),
                ('otherPopulation', models.IntegerField()),
                ('childPopulation', models.IntegerField()),
                ('teenagePopulation', models.IntegerField()),
                ('youngPopulation', models.IntegerField()),
                ('oldAgePopulation', models.IntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.warddetail')),
            ],
        ),
    ]
