# Generated by Django 4.2.7 on 2023-11-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_rename_no_warddetail_wardno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agricultureLivestock', models.IntegerField()),
                ('student', models.IntegerField()),
                ('underage', models.IntegerField()),
                ('civilServant', models.IntegerField()),
                ('privateOffice', models.IntegerField()),
                ('unemployed', models.IntegerField()),
                ('labour', models.IntegerField()),
                ('foreignEmployment', models.IntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.warddetail')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uneducated', models.IntegerField()),
                ('fundamental', models.IntegerField()),
                ('preprimary', models.IntegerField()),
                ('primary', models.IntegerField()),
                ('bachelor', models.IntegerField()),
                ('master', models.IntegerField()),
                ('technicalSLC', models.IntegerField()),
                ('generalEducation', models.IntegerField()),
                ('underAge', models.IntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.warddetail')),
            ],
        ),
    ]
