# Generated by Django 4.2.7 on 2023-11-21 10:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_mundetail_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangPop',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('palika', models.CharField(blank=True, max_length=80, null=True)),
                ('distric', models.CharField(blank=True, max_length=80, null=True)),
                ('gapa_na', models.CharField(blank=True, max_length=80, null=True)),
                ('gn_type', models.CharField(blank=True, max_length=80, null=True)),
                ('provinc', models.IntegerField(blank=True, null=True)),
                ('distrct', models.CharField(blank=True, max_length=80, null=True)),
                ('type_gn', models.CharField(blank=True, max_length=80, null=True)),
                ('ttl_fmly', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('totl_hs', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ttl_ppl', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('totl_ml', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('totl_fml', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'dang_pop',
                'managed': False,
            },
        ),
    ]
